### ISSUE TITLE
auth-file settings ignored

### ISSUE THREAD

**Issue by CountMurphy** [binwiederhier/ntfy#1040]
:lady_beetle: **Describe the bug**
Just installed on Arch by the ntfysh package. My `/etc/ntfy/server.yml` has the following three lines:

```yml
listen-http: ":8082"
auth-file: "/Raid/ntfy/user.db" 
auth-default-access: "deny-all"
```

Now the server does indeed start on port 8082, so I know ntfy is reading the config.  The permissions on the directory are 

```
drwxr-xr-x ntfy ntfy
```

When I attempt to create a new user with `ntfy user add --role=admin Name` I get:

```
option auth-file not set; auth is unconfigured for this server
```

The user.db file is also not created at service start. 

:computer: **Components impacted**

ntfy server
:bulb: **Screenshots and/or logs**

:crystal_ball: **Additional context**

Additionally, the deny-all setting is also ignored and the server is publicly accessible.
