### ISSUE TITLE
Login is disabled when NTFY_ENABLE_LOGIN: true

### ISSUE THREAD

**Issue by akarabach** [binwiederhier/ntfy#1075]
:lady_beetle: **Describe the bug**
```

version: "3"

services:
  ntfy:
    image: binwiederhier/ntfy
    container_name: ntfy
    command:
      - serve
    environment:
      NTFY_BASE_URL: https://ntfy.qwe.com
      NTFY_CACHE_FILE: /var/lib/ntfy/cache.db
      NTFY_AUTH_FILE: /var/lib/ntfy/user.db
      NTFY_AUTH_DEFAULT_ACCESS: deny-all
      NTFY_ATTACHMENT_CACHE_DIR: /var/lib/ntfy/attachments
      **NTFY_ENABLE_LOGIN: 'true'**
      NTFY_UPSTREAM_BASE_URL: https://ntfy.sh
    volumes:
      - /mnt/user/appdata/ntfy/cache:/var/cache/ntfy
      - /mnt/user/appdata/ntfy/etc:/etc/ntfy
      - /mnt/user/appdata/ntfy/lib:/var/lib/ntfy
    restart: always
```

When I'm trying to navigate to https://ntfy.qwe.com/login - I see screen login is disabled. Main url is not protected either.

:bulb: **Screenshots and/or logs**
no errors in logs 

<img width="513" alt="Screenshot 2024-03-28 at 23 59 14" src="https://github.com/binwiederhier/ntfy/assets/12261380/45fa1e15-7ee3-406c-8701-0f9335df52d3">
