### ISSUE TITLE
config ignored for non-root users, no debug output!?

### ISSUE THREAD

**Issue by bobemoe** [binwiederhier/ntfy#1192]
:lady_beetle: **Describe the bug**

I have set `/etc/ntfy/client.yml` with a custom `default-host` and `default-token` and when i run as root `ntfy pub test test` it works just fine!

The issue is when I run as a normal user it seems to be ignoring `/etc/ntfy/client.yml` and publishing to `ntfy.sh` rather than my custom server.

I have confirmed my normal user can read  `/etc/ntfy/client.yml` and that no `~/.config/ntfy/client.yml` or ENV vars are overriding the config.

Additionally I try to debug with --debug and --trace but these add no extra output.

It works if I:
```
mkdir ~/.config/ntfy
cp /etc/ntfy/client.yml ~/.config/ntfy/
```
But I dont want to have to do that for all users :/

:computer: **Components impacted**

Devuan Linux, server running in docker and client using static binaries.
ntfy 2.11.0 (d11b100), runtime go1.22.2, built at 2024-05-13T20:16:12Z

:bulb: **Screenshots and/or logs**

```
$ ntfy --debug --trace pub test test
{"id":"ABga54IscnkW","time":1727711598,"expires":1727754798,"event":"message","topic":"test","message":"test"}
```

:crystal_ball: **Additional context**

```
services:
  ntfy:
    image: binwiederhier/ntfy
    restart: unless-stopped
    environment:
      NTFY_BASE_URL: http://ntfy.xxxx.co.uk
      NTFY_CACHE_FILE: /var/lib/ntfy/cache.db
      NTFY_AUTH_FILE: /var/lib/ntfy/auth.db
      NTFY_AUTH_DEFAULT_ACCESS: deny-all
      NTFY_BEHIND_PROXY: true
      NTFY_ATTACHMENT_CACHE_DIR: /var/lib/ntfy/attachments
      NTFY_ENABLE_LOGIN: true
    volumes:
      - ./data/:/var/lib/ntfy
    ports:
      - 9753:80
    command: serve

```
