### ISSUE TITLE
Topic-specific Configurations

### ISSUE THREAD

**Issue by tentme** [binwiederhier/ntfy#1214]
:bulb: **Idea**

As the title suggests, this will allow admin to specify custom attachment size limits, expiration times, etc. for individual topics.

For example, via `server.yml`:
```yaml
topics:
  my_topic:
    attachment-file-size-limit: 20MB
    attachment-expiry-duration: 12h
  another_topic:
    attachment-file-size-limit: 5MB
    attachment-expiry-duration: 1h
```
Or, like `auth-file`, these configurations could be put into a `.db` file and modified dynamically via the ntfy CLI.

I imagine this could provide more flexibility and better resource management. And it would cool if this implemented like **Tiers**.
