### ISSUE TITLE
Incorrect Kustomize config files in the docs

### ISSUE THREAD

**Issue by toby-griffiths** [binwiederhier/ntfy#1367]
:lady_beetle: **Describe the bug**

Not sure is this is the right place, but there's a bug in the example Kustomize config files in the docs found [here](https://docs.ntfy.sh/install/#kustomize).

:computer: **Components impacted**

Kubernetes deployment via Kustomize.

:bulb: **Screenshots and/or logs**

The config file is mapped to `/etc/ntfy`, rather than `/etc/ntfy/server.yml` via these line in the `ntfy-deployment.yaml` file…

```yaml
apiVersion: apps/v1
kind: Deployment
spec:
  template:
    spec:
      containers:
        - name: ntfy
          volumeMounts:
            - mountPath: /etc/ntfy # <== I HAD TO CHANGE TO /etc/ntfy/server.yml
              subPath: server.yml
```

And the indentation on the `spec.template.spec.volumes` section is slightly too large, and should be indented by 2 less spaces.

:crystal_ball: **Additional context**

I discovered these whilst deploying ot my local minikube server.

```shell
$ minikube version
minikube version: v1.36.0
commit: f8f52f5de11fc6ad8244afac475e1d0f96841df1
```

I hope this info is useful.
