### ISSUE TITLE
do not overwrite server.yaml

### ISSUE THREAD

**Issue by waclaw66** [binwiederhier/ntfy#166]
Hi,
could you please enhance rpm install script to not overwrite /etc/ntfy/server.yaml configuration. Instead of it create server.rpmnew in the usual way?

Thanks.

**Comment by waclaw66** [comment]
I think `noreplace` can be used or specify them according docs...
``` yaml
      # These config files will not be replaced by new versions if they were
      # changed by the user. Corresponds to %config(noreplace).
      config_noreplace_files:
        path/to/local/bar.con: /etc/bar.conf
```
I can check it if you provide a test rpm for x86_64.
