### ISSUE TITLE
Ansible action plugin to post messages to ntfy.sh

### ISSUE THREAD

**Issue by jpmens** [binwiederhier/ntfy#454]
I thought this might interest people: I've created a small Ansible action plugin which can post messages to `ntfy.sh`. (I'm aware the `uri` module can do this as well but think this is a bit simpler to use.)

```yaml
- name: "Notify ntfy that we're done"
  ntfy:
        msg: "deployment on {{ inventory_hostname }} is complete. 🐄"
        attrs:
           tags: [ heavy_check_mark ]
           priority: 1
```

![rabbit-9699](https://user-images.githubusercontent.com/60706/198824486-2c5f8083-cc27-4ccf-a909-964881ea936b.png)

Feedback and suggestions / improvements are welcome at [https://github.com/jpmens/ansible-ntfy](https://github.com/jpmens/ansible-ntfy)
