### ISSUE TITLE
Empty bind mounted directories and no server.yml?

### ISSUE THREAD

**Issue by DoTheEvo** [binwiederhier/ntfy#624]
ntfy works and all is fine, but my bind mounted directories are empty, is it normal?

<details>
<summary>here is my docker-compose.yml</summary>

```yml
services:

  ntfy:
    image: binwiederhier/ntfy
    container_name: ntfy
    hostname: ntfy
    env_file: .env
    restart: unless-stopped
    command:
      - serve
    volumes:
      - ./ntfy_cache:/var/cache/ntfy
      - ./ntfy_etc:/etc/ntfy
    expose:
      - 80:80

networks:
  default:
    name: caddy_net
    external: true
```
</details>

I tried adding `user: root` just to see if its not permission issue, but no change.
I am kinda confused on this, as when I down it and recreate the stuff is there... but apparently its saved by browser and in another browser its not there.

Interesting, though something is not right about this if I would want to go with users and passwords
