### ISSUE TITLE
Panic: toFirebaseMessage

### ISSUE THREAD

**Issue by binwiederhier** [binwiederhier/ntfy#641]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x84aa2d]

goroutine 86 [running]:
heckel.io/ntfy/user.(*Manager).Authorize(0x0, 0x1?, {0xc00033fb85, 0x11}, 0x1)
        /home/runner/work/ntfy/ntfy/user/manager.go:748 +0xcd
heckel.io/ntfy/server.toFirebaseMessage(0xc000726900, {0x24db810?, 0x0?})
        /home/runner/work/ntfy/ntfy/server/server_firebase.go:143
 +0xc7
heckel.io/ntfy/server.(*firebaseClient).Send(0xc000830e40, 0xc00050a030?, 0xfb5f81?)
        /home/runner/work/ntfy/ntfy/server/server_firebase.go:44 +0x67

heckel.io/ntfy/server.(*Server).sendToFirebase(0xc0004ed3f0, 0x0?, 0x0?)
        /home/runner/work/ntfy/ntfy/server/server.go:
670 +0x129
created by heckel.io/ntfy/server.(*Server).handlePublishWithoutResponse
        /home/runner/work/ntfy/ntfy/server/server.go:625 +0x10fb
```

```yml
base-url: "https://ntfy.mydomain.com"
cache-file: "/var/cache/ntfy/cache.db"
attachment-cache-dir: "/var/cache/ntfy/attachments"
cache-duration: "48h"
firebase-key-file: "/etc/ntfy/ntfy-123456789ABCDEF.json"

behind-proxy: true
listen-http: ":2586"
```

Reported via Reddit: https://www.reddit.com/r/ntfy/comments/11drjvv/segmentation_violation/
