### ISSUE TITLE
NTFY_WEB_ROOT: setting an alternative web root means any URL used gets a subscription added by that name, is this by design?

### ISSUE THREAD

**Issue by mannp** [binwiederhier/ntfy#765]
Hi there

I have configured my self-hosted instance with the following config;
```
    env:
      TZ: "${TIMEZONE}"
      NTFY_BEHIND_PROXY: true
      NTFY_BASE_URL: "https://ntfy.${SECRET_PROD_DOMAIN_XYZ}"
      NTFY_AUTH_DEFAULT_ACCESS: deny-all
      NTFY_AUTH_FILE: /var/lib/ntfy/user.db
      NTFY_ATTACHMENT_CACHE_DIR: /var/cache/ntfy
      NTFY_WEB_ROOT: /app # or app
      NTFY_ENABLE_SIGNUP: false
      NTFY_ENABLE_LOGIN: false
```

The strange thing is I enter the url: https://ntfy.${SECRET_PROD_DOMAIN_XYZ}/ghdfdfghdfjk

I get the ui displayed with a subscription added named: ghdfdfghdfjk

Is this by design, as I would like to have / open and /app the url for the ui.

Thanks in advance
