### ISSUE TITLE
Nullify / unset `default-user` and `default-password` in client configuration?

### ISSUE THREAD

**Issue by tomeon** [binwiederhier/ntfy#829]
:question: **Nullify / unset `default-user` and `default-password` in client configuration** :question:

First, thanks for `ntfy`  -- it was easy to set up a self-hosted instance and has been a real treat to use.

I am using `ntfy` version 2.5.0 on NixOS 23.05.  Here's my situation, slightly fictionalized for brevity and security:

```yaml
--- 
# ~/.config/ntfy/client.yml

default-user: myuser
default-password: hunter2
default-host: https://ntfy.local # self-hosted, LAN-only
default-command: issue-desktop-notification

subscribe:
  - topic: thing
  - topic: other-thing
  - topic: yet-another-thing
  - topic: https://ntfy.sh/needs-to-use-public-host-for-reasons
    user: ??? # don't use `user` for public instance
    password: ??? # don't use `password` for public instance
```

My question is: what, if anything, can I use in place of the `???`s above in order to disable authentication for the topic `https://ntfy.sh/needs-to-use-public-host-for-reasons`?  I've tried using each of the four combinations in the Cartesian product of  `{"", null} x {"", null}` for `user` and `password`, but none them work (which is to say that I continue to get `401`s from `ntfy sub --from-config`).

Am I holding it wrong?  Or is this not possible at present?  I can of course list `user` and `password` for each of the subscriptions on my self-hosted instance, which is effective but cumbersome.

Thank you!
