### ISSUE TITLE
Adding `auth-file: "/var/lib/ntfy/user.db" auth-default-access: "read-write"` in docker instance problems.

### ISSUE THREAD

**Issue by kaumudpa** [binwiederhier/ntfy#865]
Hi,

On a docker instance If we add 
`auth-file: "/var/lib/ntfy/user.db"`
`auth-default-access: "read-write"`

to the server.yml file  The docker instance fails to restart. and when these files are removed it works perfectly fine.

**Comment by anubis619** [comment]
The problem seems to be the 
auth-file: "/var/lib/ntfy/user.db"

If I leave the second one the docker container starts. But can't get the auth part to work ^^

**Comment by wunter8** [comment]
It might be easier to solve this on Discord. But it seems like you're not correctly mounting the /var/lib/ntfy directory inside the Docker container. Or you might be mounting it but the user that is running the container may not have access to that directory. I'd need to know more about your setup

**Comment by kaumudpa** [comment]
Its a simple docker instance spinned up via` docker-compose` as fund here https://docs.ntfy.sh/install/#docker

**Comment by kaumudpa** [comment]
As suggested by @wunter8 on discord.

When using Docker,  it's easier to use environment variables to configure everything instead of server.yml. Here's an example docker-compose.yml file with some good default settings.

Working docker-compose config.

```
version: '3'
services:
  ntfy:
    image: binwiederhier/ntfy
    restart: unless-stopped
    environment:
      NTFY_BASE_URL: <base_url>
      NTFY_AUTH_FILE: /etc/ntfy/auth.db
      NTFY_AUTH_DEFAULT_ACCESS: read-write
      NTFY_BEHIND_PROXY: true
      NTFY_ATTACHMENT_CACHE_DIR: /etc/ntfy/attachments
      NTFY_UPSTREAM_BASE_URL: https://ntfy.sh
      NTFY_ENABLE_LOGIN: true
      NTFY_WEB_PUSH_PUBLIC_KEY: <public_key>
      NTFY_WEB_PUSH_PRIVATE_KEY: <private_key>
      NTFY_WEB_PUSH_FILE: /etc/ntfy/webpush.db
      NTFY_WEB_PUSH_EMAIL_ADDRESS: <email>
    volumes:
      - ./:/etc/ntfy
    ports:
      - 8093:80
    command: serve
```

All credits to @wunter8 for this solution.
