### ISSUE TITLE
iOS not pushing notifications.  Ntfy needs to be refreshed to view them.

### ISSUE THREAD

**Issue by g0d1k** [binwiederhier/ntfy#880]
:lady_beetle: **Describe the bug**

:computer: **Components impacted**

:bulb: **Screenshots and/or logs**

:crystal_ball: **Additional context**

**Comment by naxels** [comment]
I noticed something similar today: iOS itself would show the notification,
however, opening the app (having it open previously + on the subscribed topic)
would not show the notification even upon refresh of the list.

Closing the app & reopening it, would show the notification in the topic.

**Comment by kevinlutzer** [comment]
I am experiencing the same issue. I am running in a Kubernetes environment and here is my ConfigMap. 

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: ntfy
  namespace: ntfy
data:
  server.yml: |
    base-url: "https://myurl.com"
    upstream-base-url: "https://ntfy.sh"
    log-level: debug
```

I was able to refresh the subscription by pulling down on the view in IOS.
